spring.application.name=demo
spring.datasource.url=jdbc:postgresql://localhost:5432/student_db
spring.datasource.username=postgres
spring.datasource.password=password

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true

jwt.secret=4b8d7d5d1f6b8c3a9e7f2c4d8a6b1e5f9c7d2a4b6e8f1c3d5a7b9e2f4c6d8a1
jwt.expiration=86400000